### ISSUE TITLE
delete unused data from actual csv file?

### ISSUE THREAD

**Issue by JosieMcClellan** [izaxveta/bike-share#85]
In a utility script, as opposed to just ignoring the data... would be quicker to seed each time, less code in seed file, less storage.

**Comment by s-espinosa** [comment]
@JosiMcClellan I'm o.k. with this.

I hate the idea of deleting/losing data (who knows what we'll need in the future), and I would want to make sure we had the full data set available somewhere. However, given that we've already made the decision not to seed the DB with all of the columns, and I know that we currently have the data set backed up elsewhere, I'm o.k. with deleting it in this particular case.

One note: this would likely not be highest on my priority list. Make sure that the team discusses your timeline and sets a schedule for when to have specific tasks completed. I would tackle this if you're ahead of schedule on other tasks.

Intrigued to see how much time you pick up in seeding from just this change!

**Comment by icorson3** [comment]
I am also intrigued! This is very forward-thinking! 🎉
